<script src="<?php echo PATTERNS::getVD();?>vendor/adminbsb/plugins/jquery/jquery.min.js"></script>
<script src="<?php echo PATTERNS::getVD();?>vendor/adminbsb/plugins/bootstrap/js/bootstrap.js"></script>
<script src="<?php echo PATTERNS::getVD();?>vendor/adminbsb/plugins/bootstrap-select/js/bootstrap-select.js"></script>
<script src="<?php echo PATTERNS::getVD();?>vendor/adminbsb/plugins/jquery-slimscroll/jquery.slimscroll.js"></script>
<script src="<?php echo PATTERNS::getVD();?>vendor/adminbsb/plugins/node-waves/waves.js"></script>
<script src="<?php echo PATTERNS::getVD();?>vendor/adminbsb/plugins/jquery-countto/jquery.countTo.js"></script>
<script src="<?php echo PATTERNS::getVD();?>vendor/adminbsb/plugins/raphael/raphael.min.js"></script>
<script src="<?php echo PATTERNS::getVD();?>vendor/adminbsb/plugins/morrisjs/morris.js"></script>
<script src="<?php echo PATTERNS::getVD();?>vendor/adminbsb/plugins/chartjs/Chart.bundle.js"></script>
<script src="<?php echo PATTERNS::getVD();?>vendor/adminbsb/plugins/flot-charts/jquery.flot.js"></script>
<script src="<?php echo PATTERNS::getVD();?>vendor/adminbsb/plugins/flot-charts/jquery.flot.resize.js"></script>
<script src="<?php echo PATTERNS::getVD();?>vendor/adminbsb/plugins/flot-charts/jquery.flot.pie.js"></script>
<script src="<?php echo PATTERNS::getVD();?>vendor/adminbsb/plugins/flot-charts/jquery.flot.categories.js"></script>
<script src="<?php echo PATTERNS::getVD();?>vendor/adminbsb/plugins/flot-charts/jquery.flot.time.js"></script>
<script src="<?php echo PATTERNS::getVD();?>vendor/adminbsb/plugins/jquery-sparkline/jquery.sparkline.js"></script>
<script src="<?php echo PATTERNS::getVD();?>js/functions.lib.js?<?php echo microtime();?>"></script>
<script>jsLIB.rootDir = '<?php echo PATTERNS::getVD();?>';</script>
<script src="<?php echo PATTERNS::getVD();?>js/notifications.lib.js?<?php echo microtime();?>"></script>
<script src="./index.js?<?php echo microtime();?>"></script>
